### ISSUE TITLE
Error in pip install -r requirements.txt

### ISSUE THREAD

**Issue by cs-mshah** [GGGHSL/GraphDreamer#2]
ERROR: Could not find a version that satisfies the requirement clip==1.0 (from versions: 0.0.1, 0.1.0, 0.2.0)
ERROR: No matching distribution found for clip==1.0

**Comment by cs-mshah** [comment]
Currently using the following workaround: https://github.com/YBYBZhang/ControlVideo/issues/19#issuecomment-1666510243

**Comment by GGGHSL** [comment]
Thank you for pointing out the issue. We've updated the installation code. Please check it out.
