### ISSUE TITLE
A lot of conflicting dependencies

### ISSUE THREAD

**Issue by adeerkhan** [GGGHSL/GraphDreamer#3]
I am getting constantly conflicting dependency issues, such as Clip, Taichi, etc: 
```
The conflict is caused by:
    The user requested torch==2.0.1
    accelerate 0.19.0 depends on torch>=1.6.0
    carvekit-colab 4.1.0 depends on torch
    controlnet-aux 0.0.7 depends on torch
    functorch 0.2.1 depends on torch<1.13 and >=1.12.1
```
I think both the Readme file and the Requirments.txt file do not correlate with each other, both mention different dependency versions.

**Comment by GGGHSL** [comment]
Thank you for pointing out the issue. We've updated the installation code. Please check it out.
