### ISSUE TITLE
DeepFloyd/IF-I-XL-v1.0 Error

### ISSUE THREAD

**Issue by adeerkhan** [GGGHSL/GraphDreamer#5]
I am getting the following errors:

`OSError: Cannot load model DeepFloyd/IF-I-XL-v1.0: model is not cached locally and an error occured while trying to fetch metadata from the Hub. Please check out the root cause in the stacktrace above.`

and this error:

```
Traceback (most recent call last):
  File "/workspace/GraphDreamer/launch.py", line 181, in <module>
    main()
  File "/workspace/GraphDreamer/launch.py", line 109, in main
    system: BaseSystem = threestudio.find(cfg.system_type)(
  File "/workspace/GraphDreamer/threestudio/systems/base.py", line 40, in __init__
    self.configure()
  File "/workspace/GraphDreamer/threestudio/systems/gdreamer.py", line 63, in configure
    prompt_processor = threestudio.find(self.cfg.prompt_processor_type)(self.cfg.prompt_processor)
  File "/workspace/GraphDreamer/threestudio/utils/base.py", line 83, in __init__
    self.configure(*args, **kwargs)
  File "/workspace/GraphDreamer/threestudio/models/prompt_processors/base.py", line 298, in configure
    with open(os.path.join("load/prompt_library.json"), "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'load/prompt_library.json'
```

**Comment by GGGHSL** [comment]
Thanks for pointing this out. We have just uploaded the missing file `load/prompt_library.json`.

**Comment by adeerkhan** [comment]
> Thanks for pointing this out. We have just uploaded the missing file `load/prompt_library.json`.

How do I resolve the DeepFloyd/IF-I-XL-v1.0 error?

**Comment by GGGHSL** [comment]
To use [DeepFloyd IF](https://github.com/deep-floyd/IF?tab=readme-ov-file) you currently need to accept its usage conditions. To do so, make sure to have a [Hugging Face account](https://huggingface.co/welcome) (login in the terminal by `huggingface-cli login`) and accept the license on the model card of [DeepFloyd/IF-I-XL-v1.0](https://huggingface.co/DeepFloyd/IF-I-XL-v1.0). 
We've also updated the usage instruction, thanks.
