### ISSUE TITLE
About individualized object fields encoding in sec4.2

### ISSUE THREAD

**Issue by VivianGemLee** [GGGHSL/GraphDreamer#8]
Thanks for amazing work!
I would like to ask, during the optimization process of the implicit field, are both multi-resolution hash grid encoding(from Instant NGP) and the shared shallow MLPs(for SDF and color prediction) training simultaneously? And how are they initialized?

**Comment by GGGHSL** [comment]
Hello, thanks for asking. For the first question, yes, both the encoding networks and the MLPs are trained simultaneously. The hash encoders are randomly initialized (according to a seed), and the MLPs are using Kaiming-uniform distribution.
